Repository mysociety/foi-for-councils, pull requests merged in 2021-03, with the labels that each got.

#389 [#387] Annotate models with schema information
  Gemfile
  Gemfile.lock
  app/models/contact.rb
  app/models/curated_link.rb
  app/models/foi_request.rb
  app/models/foi_suggestion.rb
  app/models/performance.rb
  app/models/published_request.rb
  app/models/resource.rb
  app/models/submission.rb
  app/models/summary.rb
  app/models/user.rb
  gemfiles/rails_main.gemfile.lock
  lib/tasks/auto_annotate_models.rake
Labels: awaiting-review

#395 [#383] Extract case management backend
  app/models/case_management/infreemation.rb
  app/models/case_management/infreemation/published_request.rb
  app/models/case_management/infreemation/submitted_request.rb
  app/models/published_request.rb
  app/services/deliver_submission.rb
  app/services/disclosure_log.rb
  spec/models/case_management/infreemation/published_request_spec.rb
  spec/models/case_management/infreemation/submitted_request_spec.rb
  spec/models/case_management/infreemation_spec.rb
  spec/models/published_request_spec.rb
  spec/services/deliver_submission_spec.rb
  spec/services/disclosure_log_spec.rb
Labels: awaiting-deploy

#398 Bump Infreemation gem to 0.2.3
  Gemfile.lock
  gemfiles/rails_main.gemfile.lock
Labels: dependencies

#402 [#396] Configure which case management backend will be used
  .github/workflows/ci.yml
  .gitignore
  app/models/case_management.rb
  app/models/case_management/icasework.rb
  app/models/case_management/infreemation.rb
  app/services/deliver_submission.rb
  bin/setup
  config/case_management.yml-example
  config/initializers/icasework.rb
  config/initializers/infreemation.rb
  spec/models/case_management/icasework_spec.rb
  spec/models/case_management/infreemation_spec.rb
  spec/models/case_management_spec.rb
  spec/services/deliver_submission_spec.rb
Labels: awaiting-deploy

#406 [#405] Add source to published requests
  app/models/case_management/icasework.rb
  app/models/case_management/infreemation.rb
  app/models/case_management/infreemation/published_request.rb
  app/models/published_request.rb
  app/services/disclosure_log.rb
  db/migrate/20210316124123_add_case_management_to_published_requests.rb
  db/schema.rb
  spec/factories/published_requests.rb
  spec/models/case_management/icasework_spec.rb
  spec/models/case_management/infreemation/published_request_spec.rb
  spec/models/case_management/infreemation_spec.rb
  spec/models/published_request_spec.rb
  spec/services/disclosure_log_spec.rb
Labels: awaiting-deploy

#407 Test that we persist new publish requests
  spec/services/disclosure_log_spec.rb
Labels: awaiting-deploy

#414 Use new symbolised iCasework client params
  app/models/case_management/icasework.rb
  spec/models/case_management/icasework_spec.rb
Labels: awaiting-deploy

#401 [#385] iCasework: Import Published Requests
  app/models/case_management/icasework.rb
  app/models/case_management/icasework/published_request.rb
  app/services/disclosure_log.rb
  config/initializers/case_management.rb
  spec/models/case_management/icasework/published_request_spec.rb
  spec/models/case_management/icasework_spec.rb
  spec/services/disclosure_log_spec.rb
Labels: awaiting-deploy

#417 [#413] Improve Icasework::PublishedRequest#publish_at
  app/models/case_management/icasework/published_request.rb
  spec/models/case_management/icasework/published_request_spec.rb
Labels: awaiting-deploy
